### ISSUE TITLE
Day names defaulting to none

### ISSUE THREAD

**Issue by MatMorrisParker** [TheBnl/silverstripe-openinghours#4]
I may be missing a trick here, but when I'm adding days, it originally shows up as _('none')_, and changes to 'Monday' when it's saved:
![image](https://user-images.githubusercontent.com/6892752/58814691-19b5da80-861e-11e9-8004-c35e2414a9ef.png)

Which saves them as:
![image](https://user-images.githubusercontent.com/6892752/58814709-233f4280-861e-11e9-9baa-5aac5546d065.png)

Other than that, great add-on! Really simple and nice to use.

**Comment by TheBnl** [comment]
Hi Parker!

Strange it should generate all the days of the week by itself. This now happens when the site config is saved and no days have been added. (i should probably move that to a action that is triggerd on build.. 😬)

As the objects are not deletable from the CMS you should probably clear the days table in the database and then save the config again to generate the days of the week.

Hope that's clear!
